defaults:
  - override hydra/job_logging: disabled
  
data_path: "data"
results_dir: "results"

model: "DiT-S"   # choices: [list(DiT_models.keys())]

epochs: 10
batch_size: 128
lr: 1e-4
weight_decay: 0
seed: 42
num_workers: 4
loss_scale: 1

log_every: 50
ckpt_every: 5000

wandb:
  project: "oracle"
  name: "btc_DiT-S"
  log: True